<?php
	$_bestsellers = Mage::getModel('orange_bestsellers/bestsellers');
	$_helper = $this->helper('catalog/output');
?>
<?php if($_bestsellers->isActive()): ?>
<div class="block">
	<?php if($_bestsellers->showTitle()): ?>
	<div class="block-title">
		<strong>
			<span><?php echo $_bestsellers->getTitle() ?></span>
		</strong>
	</div>
	<?php endif ?>
	<div class="block-content">
		<?php if($_bestsellers->data() && count($_bestsellers->data())): ?>
			<ol class="mini-products-list">
			<?php foreach ($_bestsellers->data() as $_product): ?>	
				<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
				<li class="item">
					<div class="product">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						<div class="product-details">
							<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
							<?php echo $this->getPriceHtml($_product, true) ?>
							<?php if($_bestsellers->addToCart()): ?>
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							<?php endif ?>
							<?php if($_bestsellers->wishlistLink() || $_bestsellers->compareLink()): ?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow() && $_bestsellers->wishlistLink()) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product) && $_bestsellers->compareLink()): ?>
									<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
								<?php endif; ?>
							</ul>
							<?php endif ?>
						</div>
					</div>
				</li>
			<?php endforeach ?>
			</ol>
			<script type="text/javascript">decorateGeneric($$('li.item'), ['odd','even','first','last'])</script>
		<?php else: ?>
			<p class="empty">No products found.</p>
		<?php endif ?>
	</div>
</div>
<?php endif ?>
